### ISSUE TITLE
CIK Lookup API broken

### ISSUE THREAD

**Issue by ermin-sakic** [sec-edgar/sec-edgar#144]
**Describe the bug**
CIK mappings / lookup API is currently broken.

**To Reproduce**

```python
>>> from secedgar.filings.cik_lookup import CIKLookup
>>> lookups = CIKLookup(['aapl', 'msft', 'Facebook'])
>>> lookups.lookup_dict

Traceback (most recent call last):
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/client/network_client.py", line 97, in get_response
    self._validate_response(response)
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/client/network_client.py", line 139, in _validate_response
    raise EDGARQueryError("The query could not be completed. "
secedgar.utils.exceptions.EDGARQueryError: The query could not be completed. There was a client-side error with your request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/filings/cik_validator.py", line 89, in _get_lookup_soup
    return self._client.get_soup(self.path, self.params)
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/client/network_client.py", line 117, in get_soup
    return BeautifulSoup(self.get_response(path, params, **kwargs).text, features='lxml')
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/client/network_client.py", line 102, in get_response
    raise EDGARQueryError()
secedgar.utils.exceptions.EDGARQueryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/client/network_client.py", line 97, in get_response
    self._validate_response(response)
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/client/network_client.py", line 139, in _validate_response
    raise EDGARQueryError("The query could not be completed. "
secedgar.utils.exceptions.EDGARQueryError: The query could not be completed. There was a client-side error with your request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/filings/cik_lookup.py", line 39, in lookup_dict
    self._lookup_dict = self._validator.get_ciks()
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/filings/cik_validator.py", line 64, in get_ciks
    result = self._get_cik(lookup)
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/filings/cik_validator.py", line 108, in _get_cik
    soup = self._get_lookup_soup(lookup)
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/filings/cik_validator.py", line 93, in _get_lookup_soup
    return self._client.get_soup(self.path, self.params)
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/client/network_client.py", line 117, in get_soup
    return BeautifulSoup(self.get_response(path, params, **kwargs).text, features='lxml')
  File "/home/ermin/.local/lib/python3.8/site-packages/secedgar/client/network_client.py", line 102, in get_response
    raise EDGARQueryError()
secedgar.utils.exceptions.EDGARQueryError
```

**Expected behavior**
Return a dict as per documentation of the API

**Desktop (please complete the following information):**
Ubuntu Linux 20.04, master branch, self-installed

**Comment by jackmoody11** [comment]
Thanks for reporting this issue @ermin-sakic. I will take a look at it.

**Comment by ermin-sakic** [comment]
Thanks for investigating @jackmoody11 . This issue is not deterministic and might have to do with the rate limiter of SEC EDGAR as described [here](https://github.com/jadchaar/sec-edgar-downloader/issues/24) and [official EDGAR SEC developer resources](https://www.sec.gov/developer#:~:text=Current%20guidelines%20limit%20each%20user,addresses%20that%20submit%20excessive%20requests).

What helped me is to serialize individual lookups and build in a short pause between the requests. Something like that should probably be done in the lower layers when running lookups for a collection of tickers. Additionally, same exception tends to be raised when fetching Fillings. Building in a small pause after requests execution helps solve that as well.

Not sure how do dimension the pause between correctly. As a rule of thumb, 0.15s might be sufficient.

Perhaps more verbose error handling due to request throughput impasse could be helpful as well.

**Comment by jackmoody11** [comment]
@ermin-sakic I believe you are right. This seems to be a rate-limiting issue. How many CIKs are you trying to look up at once? You might find [`utils.cik_map.get_cik_map`](https://github.com/sec-edgar/sec-edgar/blob/master/secedgar/utils/cik_map.py#L7) to be helpful if you are simply looking for the CIKs.

Regardless, I think that adding the option to pause in between requests should be included in the [`NetworkClient`](https://github.com/sec-edgar/sec-edgar/blob/master/secedgar/client/network_client.py) class. This shouldn't be too difficult to add.

In the meantime, it is also possible for you to create your own client class that follows the interface laid out in [`client._base.AbstractClient`](https://github.com/sec-edgar/sec-edgar/blob/master/secedgar/client/_base.py) or inherit NetworkClient and overwrite the [`get_response`](https://github.com/sec-edgar/sec-edgar/blob/639c0b75f51d3f5536ee6e4effd636047f6d5c5a/secedgar/client/network_client.py#L79) method to include a pause between each request.

I will keep this issue open until I add this functionality by default to `NetworkClient`.

**Comment by ermin-sakic** [comment]
@jackmoody11  I tried fetching around 50-100 elements in a list. That lead to a block with the blocking period lasting ~10 minutes. During that period, any requests issued to SEC EDGAR are blocked based on the source IP address.

**Comment by jackmoody11** [comment]
@ermin-sakic this should be taken care of now. Can you `pip install git+https://github.com/sec-edgar/sec-edgar.git` and run your code again to verify? I will release to PyPi after.

**Comment by ermin-sakic** [comment]
@jackmoody11 , from initial tests, I can confirm this has solved the issue with the rate limiter. Thanks for the fast fix!
