### ISSUE TITLE
error on daily

### ISSUE THREAD

**Issue by sroussey** [sec-edgar/sec-edgar#226]
**Describe the bug**
Running in a docker container (FROM python:3.9) `secedgar daily --date 20210723`

**Screenshots**
```
Traceback (most recent call last):
  File "/usr/local/bin/secedgar", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/secedgar/cli.py", line 76, in daily
    d.save(directory=directory)
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/daily.py", line 137, in save
    self._save_filings(directory,
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_index.py", line 295, in _save_filings
    urls = self._check_urls_exist()
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_base.py", line 98, in _check_urls_exist
    urls = self.get_urls()
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_index.py", line 170, in get_urls
    filings_dict = self.get_filings_dict()
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_index.py", line 140, in get_filings_dict
    idx_file = self._get_master_idx_file(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/_index.py", line 118, in _get_master_idx_file
    if self.idx_filename in self._get_listings_directory().text:
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/daily.py", line 84, in idx_filename
    return "master.{date}.idx".format(date=self._get_idx_formatted_date())
  File "/usr/local/lib/python3.9/site-packages/secedgar/filings/daily.py", line 104, in _get_idx_formatted_date
    elif self._date < datetime.date(1998, 3, 31):
TypeError: can't compare datetime.datetime to datetime.date```
```

**Comment by jackmoody11** [comment]
Should be closed with #203
