### ISSUE TITLE
ModuleNotFoundError: No module named 'secedgar.core'; 'secedgar' is not a package

### ISSUE THREAD

**Issue by smaiyaki** [sec-edgar/sec-edgar#239]
**Describe the bug**
Having import errors when trying to use the example code from the documentation.
The documentation mentions that the code below will work

```
from secedgar import FilingType, CompanyFilings
from datetime import date

filing = CompanyFilings(cik_lookup="aapl",
                        filing_type=FilingType.FILING_10K,
                        start_date=date(2015, 1, 1),
                        end_date=date(2019, 1, 1),
                        user_agent="Name (email)") 
```

I always get errors as described in this report https://github.com/sec-edgar/sec-edgar/issues/232 and using the latest `0.4.0a2` does not fix the issue..

I am therefore using this version after looking through at the code
```
from secedgar.core.company import CompanyFilings
from secedgar.core.filing_types import FilingType
from datetime import date

filing = CompanyFilings(cik_lookup="aapl",
                        filing_type=FilingType.FILING_10K,
                        start_date=date(2015, 1, 1),
                        end_date=date(2019, 1, 1),
                        user_agent="Name (email)")
```

**Expected behavior**
Filings assigned to the my_filings variable

**Screenshots**
` from secedgar.core.company import CompanyFilings
ModuleNotFoundError: No module named 'secedgar.core'; 'secedgar' is not a package`

**Comment by jackmoody11** [comment]
See #236.

**Comment by smaiyaki** [comment]
hi @jackmoody11 ,

its working only when I interact with the python interpreter but does not work when executing from a .py file even with the virtualenv activated. I will work more on this from my end

**Comment by jackmoody11** [comment]
> hi @jackmoody11 ,
> 
> 
> 
> its working only when I interact with the python interpreter but does not work when executing from a .py file even with the virtualenv activated. I will work more on this from my end

What version is shown when you `pip list`?

**Comment by smaiyaki** [comment]
hi @jackmoody11 ,

Here is the result of the `pip list` command
```
Package            Version
------------------ -----------
aiohttp            3.7.4.post0
async-timeout      3.0.1
attrs              21.2.0
beautifulsoup4     4.9.3
certifi            2021.5.30
chardet            4.0.0
charset-normalizer 2.0.4
idna               3.2
lxml               4.6.3
multidict          5.1.0
pip                21.2.4
requests           2.26.0
secedgar           0.4.0a2
setuptools         56.0.0
soupsieve          2.2.1
tqdm               4.62.2
typing-extensions  3.10.0.2
urllib3            1.26.6
yarl               1.6.3
```

and below is my current error:
```
(venv) sultanmaiyaki@192 development % python secedgar.py
Traceback (most recent call last):
  File "/Users/sultanmaiyaki/development/secedgar.py", line 1, in <module>
    from secedgar import filings, FilingType
  File "/Users/sultanmaiyaki/development/secedgar.py", line 1, in <module>
    from secedgar import filings, FilingType
ImportError: cannot import name 'filings' from partially initialized module 'secedgar' (most likely due to a circular import) (/Users/sultanmaiyaki/development/secedgar.py)
```

**Comment by jackmoody11** [comment]
Hmm...I am not able to get the same issue. Maybe try pip installing these exact versions and see if it works.

```
❯ python3
Python 3.9.0 (default, Oct 27 2020, 14:15:17) 
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from secedgar import filings, FilingType
>>> import secedgar
>>> secedgar.__version__
'0.4.0-alpha.2' 
```


```
❯ pip list
Package            Version
------------------ -----------
aiohttp            3.7.4.post0
async-timeout      3.0.1
attrs              21.2.0
autopep8           1.5.7
beautifulsoup4     4.10.0
certifi            2021.10.8
chardet            4.0.0
charset-normalizer 2.0.7
idna               3.3
lxml               4.6.3
multidict          5.2.0
pip                20.2.3
pycodestyle        2.8.0
requests           2.26.0
secedgar           0.4.0a2
setuptools         49.2.1
soupsieve          2.2.1
toml               0.10.2
tqdm               4.62.3
typing-extensions  3.10.0.2
urllib3            1.26.7
yarl               1.7.0
```

**Comment by jackmoody11** [comment]
I was not able to replicate this issue and think it may be an issue with using the virtual environment. Let me know if you find out otherwise and I will reopen.
