### ISSUE TITLE
'NoneType' object has no attribute 'upper' error running example

### ISSUE THREAD

**Issue by ajrq** [sec-edgar/sec-edgar#255]
Running code as in example on this repository

```
from secedgar import filings, FilingType

my_filings = filings(cik_lookup="aapl",
                     filing_type=FilingType.FILING_10Q,
                     user_agent="Your name (your email)")
my_filings.save('./sec-import')

```
returns the following error:
```

Traceback (most recent call last):
  File "(redacted)/import-sec.py", line 7, in <module>
    my_filings.save('./sec-import')
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/secedgar/core/company.py", line 289, in save
    urls = self.get_urls_safely()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/secedgar/core/_base.py", line 103, in get_urls_safely
    urls = self.get_urls(**kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/secedgar/core/company.py", line 231, in get_urls
    for key, cik in self.cik_lookup.lookup_dict.items()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/secedgar/cik_lookup.py", line 90, in lookup_dict
    self._lookup_dict = self.get_ciks()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/secedgar/cik_lookup.py", line 192, in get_ciks
    cik_map = get_cik_map()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/secedgar/cik_lookup.py", line 29, in get_cik_map
    return {key: {v[key].upper(): str(v["cik_str"]) for v in json_response.values()}
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/secedgar/cik_lookup.py", line 29, in <dictcomp>
    return {key: {v[key].upper(): str(v["cik_str"]) for v in json_response.values()}
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/secedgar/cik_lookup.py", line 29, in <dictcomp>
    return {key: {v[key].upper(): str(v["cik_str"]) for v in json_response.values()}
AttributeError: 'NoneType' object has no attribute 'upper'

```

Version:
```
pip3 show secedgar
Name: secedgar
Version: 0.4.0a2
```

**Comment by jackmoody11** [comment]
Thanks for reporting this. One of the tickers provided by EDGAR provides no title. Here is the code I used to debug:

```python
response = requests.get("https://www.sec.gov/files/company_tickers.json")
json_response = response.json()
print([v for v in json_response.values() if v['title'] is None])
```

For me, this prints:

`[{'cik_str': 1104206, 'ticker': 'RIGG', 'title': None}]`

I think the most elegant solution here is to just not include the CIK if there isn't a valid ticker or title. In this case, we would include "RIGG": 1104206 as a key-value pair in the ticker dictionary, but would not include the CIK for RIGG in the title dictionary, as there is no title given.

**Comment by Azam999** [comment]
still doesn't work

**Comment by Azam999** [comment]
> Thanks for reporting this. One of the tickers provided by EDGAR provides no title. Here is the code I used to debug:
> 
> ```python
> response = requests.get("https://www.sec.gov/files/company_tickers.json")
> json_response = response.json()
> print([v for v in json_response.values() if v['title'] is None])
> ```
> 
> For me, this prints:
> 
> `[{'cik_str': 1104206, 'ticker': 'RIGG', 'title': None}]`
> 
> I think the most elegant solution here is to just not include the CIK if there isn't a valid ticker or title. In this case, we would include "RIGG": 1104206 as a key-value pair in the ticker dictionary, but would not include the CIK for RIGG in the title dictionary, as there is no title given.

How was this fixed?

**Comment by jackmoody11** [comment]
You need to pip install the latest version from GitHub.

`pip install git+https://github.com/sec-edgar/sec-edgar.git`

**Comment by Azam999** [comment]
Ok
